repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: venv/bin/black
      language: script
      exclude: ^(venv/|docs/)
      types: [python]
      stages: [commit]
    - id: isort
      name: isort
      entry: venv/bin/isort
      language: script
      exclude: ^(venv/|docs/)
      types: [python]
      stages: [commit]
    - id: pytest
      name: pytest
      entry: venv/bin/pytest
      language: script
      pass_filenames: false
      always_run: true
      stages: [push]
  - repo: https://github.com/trackuity/pre-commit-pyright
    rev: '1.1.188'
    hooks:
    - id: pyright
      stages: [push]