default_stages: [commit, push]
repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: venv/bin/black
      language: script
      exclude: ^(venv/|docs/)
      types: ['python']
    - id: isort
      name: isort
      entry: venv/bin/isort
      language: script
      exclude: ^(venv/|docs/)
      types: ['python']
    - id: pytest
      name: pytest
      entry: venv/bin/pytest
      language: script
      pass_filenames: false
      always_run: true
      stages: [push]